// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	products "go-tdd/internal/products"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: product
func (_m *Service) Create(product products.Product) error {
	ret := _m.Called(product)

	var r0 error
	if rf, ok := ret.Get(0).(func(products.Product) error); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int32) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int32) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *Service) FindAll() *[]products.Product {
	ret := _m.Called()

	var r0 *[]products.Product
	if rf, ok := ret.Get(0).(func() *[]products.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]products.Product)
		}
	}

	return r0
}

// FindById provides a mock function with given fields: id
func (_m *Service) FindById(id int32) (*products.Product, error) {
	ret := _m.Called(id)

	var r0 *products.Product
	if rf, ok := ret.Get(0).(func(int32) *products.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, product
func (_m *Service) Update(id int32, product products.Product) (*products.Product, error) {
	ret := _m.Called(id, product)

	var r0 *products.Product
	if rf, ok := ret.Get(0).(func(int32, products.Product) *products.Product); ok {
		r0 = rf(id, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*products.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int32, products.Product) error); ok {
		r1 = rf(id, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
